services:
  postgres:
    image: postgres:17
    container_name: college-postgres

    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: college_db

    ports:
      - "5432:5432"

    volumes:
      - college_db_data:/var/lib/postgresql/data

    restart: unless-stopped

volumes:
  college_db_data:
